In [1]:
# 3x4 array random values
import numpy as np
a=np.random.random((3,4))
print(a)

[[0.66688302 0.50407462 0.15922314 0.89390196]
 [0.90807249 0.90744636 0.21421133 0.01569434]
 [0.50755121 0.34219083 0.67153792 0.5414469 ]]


In [ ]:
#making all zeros
import numpy as np
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#arranging
import numpy as np
a=np.arange(5,31,2)
print(a)

[ 5  7  9 11 13 15 17 19 21 23 25 27 29]


In [ ]:
#dimensions:shape:datatype
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("Dimensions:",a.ndim)
print("\nShape:",a.shape)
print("\nDatatype:",a.dtype)

Dimensions: 2

Shape: (2, 3)

Datatype: int64


In [ ]:
#flatten
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.flatten())

[1 2 3 4 5 6 7 8 9]
