In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.hstack((arr1,arr2))
print(result)

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.vstack((arr1,arr2))
print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
import numpy as np
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
result=np.dstack((arr1,arr2))
print(result)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [6]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
result=np.split(arr,3)
print(result)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [5]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[::2]) #slicing with a step of 2
print(a[::3]) #slicing with a step of 3
print(a[::4]) #slicing with a step of 4

[1 3 5 7 9]
[1 4 7]
[1 5 9]


In [4]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[2:6])

[3 4 5 6]


In [3]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[::-1]) #reversing the array

[9 8 7 6 5 4 3 2 1]


In [2]:
#Slicing multi-dimensional array
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [1]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[:2,:1])

[[1]
 [4]]


In [7]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[:,0])
print(a[0,:])
print(a[0:3:2])

[1 4 7]
[1 2 3]
[[1 2 3]
 [7 8 9]]


In [8]:
#Array indexing
#1D array
#import numpy as np
import array
a=array.array('i',[10,20,30,40,50])
print(a[0])
print(a[3])

10
40


In [9]:
#2D array
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[0,0])
print(a[2,1])

1
8


In [10]:
import numpy as np
a=np.array([10,20,30,40,50,60])
print(a[1])
print(a[-1])
print(a[1:4])

20
60
[20 30 40]


In [12]:
import numpy as np
a=np.array(([1,2,3],[4,5,6,],[7,8,9]))
print(a[(0,1)])

2


In [ ]:
#Boolean indexing
import numpy as np
a=np.array([10,20,30,40,50])
print(a[a>25])

In [11]:
#Fancy indexing
import numpy as np
a=np.array([10,20,30,40,50])
print(a[[1,3]])

[20 40]
