In [1]:
import numpy as np
a=np.array([10,20,30])
print("one dimensional")

one dimensional


In [2]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("Two Dimensional array:",a)


Two Dimensional array: [[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print("Three Dimensional array:\n",a)

Three Dimensional array:
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


In [4]:
import numpy as np
a=np.zeros((3,5))
print("One Dimensional array:\n",a)

One Dimensional array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [5]:
import numpy as np
a=np.random.random((2,2))
print("Random Value:\n",a)

Random Value:
 [[0.7822254  0.26126742]
 [0.61267071 0.57944967]]


In [6]:
import numpy as np
a=np.arange(0,60,5)
print("Sequence array:\n",a)

Sequence array:
 [ 0  5 10 15 20 25 30 35 40 45 50 55]


In [7]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Original array:\n",a)
print("\nReshaped array:\n",a.reshape(4,3))

Original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
import numpy as np
a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print("Number of dimensions:",a.ndim)

Number of dimensions: 3


In [9]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Shape of array:",a.shape)

Shape of array: (3, 4)


In [10]:
import numpy as np
a=np.array([1,2,3,4])
print("Array element type:",a.dtype)

Array element type: int64


In [11]:
import numpy as np
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
print("Size of array:",len(a))

Size of array: 3


In [12]:
import numpy as np
a=np.array([1,2,3])
b=a.astype('float64')
print(a)
print(b)
print(b.dtype)

[1 2 3]
[1. 2. 3.]
float64
